### PR TITLE
implement add score and refresh score list using API

### PR DESCRIPTION
**Pull request by devMunyi**
- Created a new game with the name of my choice by using the API, got a game ID back which I use in making rest of the API requests.
- Implemented the "Refresh" button that will get all scores for a game created from the API (receiving data from the API and parsing the JSON).
- Implemented the form "Submit" button that will save a score for a game created by you (sending data to the API).
- Used arrow functions instead of the function keyword.
- Used async and await JavaScript features to consume the API.

### CODE REVIEW

**Review by Qoosim — CHANGES_REQUESTED** [review]
#  *Status: Required Changes* :recycle: 

Hi @devMunyi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Git Flow. :heavy_check_mark: 



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] While trying to test the functionality of your app, I noticed some validation errors both in the name and score input fields. I cannot use the form to create a game without making both my name and score to be in email format. I tried to use incognito to test it but still the same error. Kindly look into it and fix where the problem is. Below are the screenshots for the validation response I am getting.

### Name input field

name

### Score input field

score


### Name input field on incognito 

incognito-name

### Score input field on incognito

incognito-score

**Comment by devMunyi** [comment]
I see there html email validations, but I don't get it why you getting that yet my form has inputs of type text:     `<form id="add-score-form" class="mt-4">
              <div class="form-group mb-4">
                <input
                  name="name"
                  id="name-input"
                  type="text"
                  class="form-control"
                  placeholder="Your name"
                  required
                />
              </div>
              <div class="form-group mb-4">
                <input
                  name="score"
                  id="score-input"
                  type="number"
                  class="form-control"
                  placeholder="Your score"
                  required
                />
              </div>

              <div class="add-score-btn__container d-flex justify-content-end">
                <button type="submit" class="btn btn-outline-primary">
                  Submit
                </button>
              </div>
            </form>`

**Comment by Qoosim** [comment]
Hmm, that's weird

**Comment by devMunyi** [comment]
> Hmm, that's weird. Is it working without asking for the validation from your side?

Yeah. Would you please try using live demo on README.md file.

**Review by mukhammadrizooff — APPROVED** [review]
Hi @devMunyi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 
- `API` is working well ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
